name: Build and deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Ensure dist exists and add CNAME
        run: |
          if [ -d "dist" ]; then
            echo "juanfuentes.dev" > dist/CNAME
          else
            echo "dist folder not found, creating and writing CNAME"
            mkdir -p dist
            echo "juanfuentes.dev" > dist/CNAME
          fi

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
